### ISSUE TITLE
ordenar produtos por categoria

### ISSUE THREAD

**Issue by mauricionr** [mauricionr/1#8]
ordenar produtos por categoria, talves criar uma base só para as categorias.
hoje quando cadastra o produto cria uma categoria, não esta usando as ja criadas.

**Comment by mauricionr** [comment]
vamos ver a melhor forma antes de fazer!

**Comment by richarddiogo** [comment]
Essa vc ja fez n foi?

**Comment by mauricionr** [comment]
vamos ver a melhor forma antes de fazer!

**Comment by mauricionr** [comment]
#criarModuloCategoria
